#!/bin/sh

. ./version_spec.mk

make -j4 zImage dtbs modules \
    CROSS_COMPILE=arm-none-linux-gnueabi- \
    ARCH=arm \
	&& echo "Constructing bootloader..." \
	&& cat arch/arm/boot/zImage > bootloader \
	&& cat arch/arm/boot/dts/imx6dl-novena-aqs.dtb >> bootloader

if [ $? -eq 0 ]
then
	cp bootloader ${NOVENTDS_VERSION}.bin
fi
